#!/usr/bin/env bash
# Copy the RunPod worker's build context into a checkout of the PRIVATE worker repo:
#   ops/runpod/sync.sh <checkout dir>
# Writes worker.json (the version every job reports back) and a README saying the repo
# is generated. Commits nothing: commit, push and `gh release create v<N>` are the
# operator's (a release starts a billed build on RunPod).
set -euo pipefail
dst=${1:?usage: ops/runpod/sync.sh <checkout of the private worker repo>}
here=$(cd "$(dirname "$0")" && pwd)
repo=$(cd "$here/../.." && pwd)
[ -d "$dst/.git" ] || { echo "sync: $dst is not a git checkout" >&2; exit 1; }
for f in Dockerfile handler.py install-nodes.sh nodes.image.txt extra_model_paths.yaml \
         gw_placeholder.png; do
  cp "$here/$f" "$dst/$f"
done
sha=$(git -C "$repo" rev-parse --short=12 HEAD)
dirty=$(git -C "$repo" status --porcelain -- ops/runpod | head -c1)
ver="$sha${dirty:+-dirty}"
nodes_sha=$(sha256sum "$here/nodes.image.txt" | cut -d' ' -f1)
py=$(sed -n 's/^ARG PY_VER=//p' "$here/Dockerfile")
torch=$(sed -n 's/^ARG TORCH_VER=//p' "$here/Dockerfile")
cuda=$(sed -n 's/^ARG TORCH_CUDA=//p' "$here/Dockerfile")
comfy=$(sed -n 's/^ARG COMFY_COMMIT=//p' "$here/Dockerfile")
cat >"$dst/worker.json" <<EOT
{"version": "$ver", "profile": "image",
 "stack": {"python": "$py", "torch": "$torch", "cuda": "$cuda", "comfy": "$comfy"},
 "nodes_sha256": "$nodes_sha"}
EOT
cat >"$dst/README.md" <<'EOT'
# ai-hub RunPod worker (generated)

Generated by `ops/runpod/sync.sh` in ai-hub — **never edit by hand**; change
`ops/runpod/` there and sync again. A GitHub release of this repo builds the image on
RunPod (Serverless → GitHub integration).
EOT
echo "synced $ver into $dst — next: cd $dst && git add -A && git commit -m 'worker $ver' && git push && gh release create v<N>"
